#!/bin/bash
# Author: Ilya Doshchinsky
# Version: 1.1.0
WakeOnLan() {
  while read tmp_string; do
    hostname=$(echo $tmp_string | awk '{print $1;}')
    addr=$(echo $tmp_string | awk '{print $2;}')
    PROBE_PING=`ping -s 1 -c 2 $hostname &> /dev/null; echo $?`
    if [ $PROBE_PING -eq 1 ];then
      ether-wake -i enp3s0 $addr
    fi
  done < $addr_path
  while read tmp_string; do
    hostname=$(echo $tmp_string | awk '{print $1;}')
    addr=$(echo $tmp_string | awk '{print $2;}')
    PROBE_PING=`ping -s 1 -c 2 $hostname &> /dev/null; echo $?`
    if [ $PROBE_PING -eq 1 ];then
      echo "$(date +%D\ %H:%M) : Host $hostname did not recieve WoL-packet or someone shut it down." >> ./log/$(date +%d%m%Y).log
    fi
  done < $addr_path
}
SendShutdown() {
  while read tmp_string; do
    hostname=$(echo $tmp_string | awk '{print $1;}')
    PROBE_PING=`ping -s 1 -c 2 $hostname &> /dev/null; echo $?`
    if [ $PROBE_PING -eq 0 ];then
      (ssh -n -o "BatchMode=yes" -o "ConnectTimeout=1" -o "StrictHostKeyChecking=no" $hostname shutdown 0 >& /dev/null)
    fi
  done < $addr_path
  while read tmp_string; do
    hostname=$(echo $tmp_string | awk '{print $1;}')
    PROBE_PING=`ping -s 1 -c 2 $hostname &> /dev/null; echo $?`
    if [ $PROBE_PING -eq 0 ];then
      echo "$(date +%D\ %H:%M) : Host $hostname shutdown incomplete" >> ./log/$(date +%d%m%Y).log
    fi
  done < $addr_path
}
WhoIsOnline() {
  OnlineAmount=0
  TotalHosts=0
  OnlineHosts=()
  while read tmp_string; do
    TotalHosts=$((TotalHosts+1))
    hostname=$(echo $tmp_string | awk '{print $1;}')
    PROBE_PING=`ping -s 1 -c 2 $hostname &> /dev/null; echo $?`
    if [ $PROBE_PING -eq 0 ];then
      OnlineAmount=$((OnlineAmount+1))
      OnlineHosts+="$hostname "
    fi
  done < $addr_path
  # Checking last user logged in. Coming soon
  for host in $OnlineHosts; do
    WhoIs=$(ssh -n -o "BatchMode=yes" -o "ConnectTimeout=1" -o "StrictHostKeyChecking=no" $host who 2> /dev/null | awk '{print $1;}')
    echo "$(date +%D\ %H:%M) : User $WhoIs did not shutdown host $host." >> ./log/"BAN_LIST_"$(date +%d%m%Y).log
  done
}
#---------------------
# Start of the script
#---------------------
addr_path="/root/manage-classes/OStRTA/conf/addr.dat"
ACTION=0
while [ -n "$1" ]; do
  case "$1" in
    -w) ACTION=1
    if [ -n "$2" ]; then
      if [ -f "conf/$2" ]; then
        addr_path="conf/$2"
      else
        exit 2
      fi
    fi
    shift;;
    -s)
    if [[ ACTION -eq 1 ]]; then
      exit 3
    else
      ACTION=2
    fi
    if [ -n "$2" ]; then
      if [ -f "conf/$2" ]; then
        addr_path="conf/$2"
      else
        exit 2
      fi
    fi
    shift;;
    -l) ACTION=3
    if [ -n "$2" ]; then
      if [ -f "conf/$2" ]; then
        addr_path="conf/$2"
      else
        exit 2
      fi
    fi
    shift;;
    *) exit 4;;
  esac
  shift
done
# Command execution
if [[ ACTION -eq 1 ]]; then
  WakeOnLan
elif [[ ACTION -eq 2 ]]; then
  SendShutdown
elif [[ ACTION -eq 3 ]]; then
  WhoIsOnline
else
  exit 5
fi
exit 0
